# Generated by Django 3.2.8 on 2021-10-20 06:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import stock.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('setup_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('stock_transfer_no', models.CharField(default=stock.models.stock_transfer_no, max_length=100, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('stock_transfer_date', models.DateField(blank=True, null=True)),
                ('transfer_qty', models.DecimalField(decimal_places=2, max_digits=20)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('from_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='warehouse_from_warehouse', to='setup_data.warehouse')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='setup_data.products')),
                ('to_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='warehouse_to_warehouse', to='setup_data.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='StockPrime',
            fields=[
                ('transaction_no', models.CharField(default=stock.models.transaction_no_stock_prime, max_length=100, primary_key=True, serialize=False)),
                ('ref_number', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('stock_in_date', models.DateField(blank=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total_amount_tk', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('stock_transaction_type', models.CharField(blank=True, max_length=100, null=True)),
                ('sign', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='setup_data.products')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='setup_data.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('transaction_no', models.CharField(default=stock.models.transaction_no, max_length=100, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('stock_in_date', models.DateField(blank=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=20)),
                ('file_no', models.CharField(max_length=100)),
                ('lc_per_dollar_cost_tk', models.DecimalField(decimal_places=2, max_digits=20)),
                ('lc_unit_cost_usd', models.DecimalField(decimal_places=2, max_digits=20)),
                ('lc_unit_cost_tk', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total_amount_tk', models.DecimalField(decimal_places=2, max_digits=20)),
                ('is_active', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='setup_data.products')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='setup_data.warehouse')),
            ],
            options={
                'unique_together': {('stock_in_date', 'file_no', 'product')},
            },
        ),
        migrations.CreateModel(
            name='LC',
            fields=[
                ('lc_transaction_no', models.CharField(default=stock.models.lc_transaction_no, max_length=100, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('lc_date', models.DateField(blank=True, null=True)),
                ('lc_process_date', models.DateField(blank=True, null=True)),
                ('lc_close_date', models.DateField(blank=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=20)),
                ('file_no', models.CharField(max_length=100)),
                ('lc_per_dollar_cost_tk', models.DecimalField(decimal_places=2, max_digits=20)),
                ('lc_unit_cost_usd', models.DecimalField(decimal_places=2, max_digits=20)),
                ('lc_unit_cost_tk', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total_amount_tk', models.DecimalField(decimal_places=2, max_digits=20)),
                ('status', models.CharField(default='Open', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='setup_data.products')),
            ],
            options={
                'unique_together': {('file_no', 'lc_date', 'product')},
            },
        ),
    ]
