# Generated by Django 3.2.8 on 2021-10-15 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import stock.models


class Migration(migrations.Migration):

    dependencies = [
        ('setup_data', '0003_warehouse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lc',
            unique_together={('file_no', 'date', 'product')},
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('transaction_no', models.CharField(default=stock.models.transaction_no, max_length=100, primary_key=True, serialize=False)),
                ('ref_number', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('stock_in_date', models.DateField(blank=True, null=True)),
                ('file_no', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=20)),
                ('lc_per_dollar_cost_tk', models.DecimalField(decimal_places=2, max_digits=20)),
                ('lc_unit_cost_usd', models.DecimalField(decimal_places=2, max_digits=20)),
                ('lc_unit_cost_tk', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total_amount_tk', models.DecimalField(decimal_places=2, max_digits=20)),
                ('unit_sales_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('unit_sales_profit', models.DecimalField(decimal_places=2, max_digits=20)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('sign', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='setup_data.products')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='setup_data.warehouse')),
            ],
        ),
    ]
