# Generated by Django 3.2.8 on 2021-10-15 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20211015_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='unit_sales_price',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='unit_sales_profit',
        ),
        migrations.AlterField(
            model_name='stock',
            name='file_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
