# Generated by Django 3.2.8 on 2021-10-20 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sales.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('setup_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesParent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('order_date', models.DateField(blank=True, null=True)),
                ('invoice_no', models.CharField(default=sales.models.invoice_no_generate, max_length=100, primary_key=True, serialize=False)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('due_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('is_active', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='setup_data.customers')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='setup_data.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='SalesChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('order_date', models.DateField(blank=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('is_active', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('invoice_no', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sales.salesparent')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='setup_data.products')),
            ],
            options={
                'unique_together': {('product', 'invoice_no')},
            },
        ),
    ]
